### ISSUE TITLE
Consider enabling dependabot alerts for this repo

### ISSUE THREAD

**Issue by darakian** [mmoustafa/karmoji#38]
Hi, I stumbled upon this repo pseudo randomly after being tagged in a PR for some reason and figured that I should make the case for enabling updates. There's a really cool github feature called dependabot which will automate scanning for and notification of vulnerable dependencies! 😲 

It's really easy to enable through the github UI. Just go to settings -> security & analysis -> click the enable button on `Dependabot Alerts`

![image](https://user-images.githubusercontent.com/3607524/110881096-99adb180-8294-11eb-9dd8-bc02a4c5f9ac.png)
Some say that lack of maintenance can lead to unintended disaster!

If somthing is wrong you'll see useful and tasteful alerts like this!
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/3607524/110881150-b9dd7080-8294-11eb-998a-2ab023445744.png">

Don't worry about sullying the reputation of you repo either as the alerts are only visible to contributors 😉 
It's really useful to have an extra set of automatic eyes watching code that might touch sensitive information too! 👀

**Comment by mmoustafa** [comment]
Done, thank you

![CCF7C9AA-8973-418D-B13F-1553165E25E7](https://user-images.githubusercontent.com/1714782/111192770-acff9c00-8576-11eb-8484-eb6b5de3f384.jpeg)
